---
# [Transcriptomics]{style="color:purple;"}

## Author: Carolyn Hanrahan

### Affiliation: University of Vermont, RSENR

### E-mail contact: [carolyn.hanrahan\@uvm.edu](mailto:carolyn.hanrahan@uvm.edu)

### Start Date: 10/16/2023

### End Date: TBD

### Project Descriptions: This notebook markdown file will document my workflow of the bioinformatics of the Transcriptomics section of Ecological Genomics, fall 2023.

# Table of Contents:

-   [Entry 1: 2023-10-16](#id-section1)
-   [Entry 2: 2023-10-18](#id-section2)
-   [Entry 3: 2023-10-23](#id-section3)
-   [Entry 4: 2023-09-20](#id-section4)
-   [Entry 5: 2023-09-25](#id-section5)
-   [Entry 6: 2023-09-27](#id-section6)
-   [Entry 7: 2023-10-02](#id-section7)
-   [Entry 8: 2023-10-04](#id-section8)



<div id='id-section1'/>
### Entry 1: 2023-10-16.
- Transcriptomics Day 3.

- Goals for the day:
   - Review the quality of our Illumina data from our google sheet.
   - Assess our previously assembled de novo transcriptome assembly using scripts provided through Trinity.
  - Map reads and quantify abundance simultaneously using Salmon.
  - Prepare data for import into DESeq2.
  - Start analyzing the gene expression data using DESeq2


<div id='id-section2'/>
### Entry 2: 2023-10-18.
- Transcriptomics Day 4.

- Goals for the day:
    - Assemble the quant.sf files generated by salmon into a matrix to import into DESeq2.
    - Start analyzing the gene expression data using DESeq2

<div id='id-section3'/>
### Entry 3: 2023-10-23.
- Transcriptomics Day 5.

- Goals for the day:
    - Review results from filtering of the de novo assembly and transfer the new gene expression matrix.
    - Explore patterns in the gene expression data using DESeq2: explore data, plot PCA, test for DGE, make a Venn diagram.
- see "transcriptomics_day4.R" file for scripts from class (added on from day 4)


### Entry 4: 2023-09-20

-   We finished processing `bam_stats.sh` by altering the vim file and running `bash bam_stats.sh`. Following this, we examined the read data by using the head command.
-   Created an ANGSD directory and a script for running the ANGSD program to determine genotype likelihood.
-   Began running this script using `tmux` in the background.

### Entry 5: 2023-09-25

- Today's learning objectives: 
  - Calculate diversity stats for our focal pops (SFS, theta-W, theta-Pi, Tajima’s D)
  - Summarize the results in R and share to google doc
  - Introduce Fst in ANGSD using genotype probabilities

### Entry 6: 2023-09-27

- Today's learning objectives: 
  - Review the diversity stats for our focal pops on the google doc
  - Estimate genetic differentiation (Fst) in ANGSD between our focal red spruce pops and black spruce
  - Visualize population structure using PCA (principle component analysis) and Admixture
  
### Entry 7: 2023-10-02

- Today is a coding and bioinformatics day. Goals include: 
  - Review the population structure results
  - Perform a scan for selection and identify contigs with outlier loci
  - Identify and visualize outlier loci
  
## Entry 8: 2023-10-04

- Today's goals include:
  - Revisit pcANGSD selection scan to output genetic PCs and outlier loci list
  - Extract climate data for red spruce localities and summarize with PCA
  - Run genotype-environment association (GEA) analysis running
  
- Notes: 
  - Genotype data (SNPs) + environmental data (climate) --> genome wide average 
  - Env (y) = Genotype (locus specific) + covariates (genetic PCs)

- Steps for today: 
  1. in R: revisit selection outliers --> outlier list (PC1)
  2. genetic PCA --> genetic PC1 + PC2 as covariates
  3. Get bioclim environment variables 
  4. Transfer files to server -- run GEA. 
  
## Entry 9: 2023-10-09
  
- Transcriptomics unit; reading paper on Colorado Potato Beetle and insecticide resistance. 
  
- Coding goals for the day: 
  - Review Acartia hudsonica ecology and biogeography and the experimental evolution/transcriptomics experimental design.

  - Develop questions that can be addressed and hypotheses that can be tested with the A. hudsonica experiment.

  - Understand the general work flow or “pipeline” for processing and analyzing RNAseq data.

  - Visualize and interpret the quality of our Illumina data.

  - Assess our previously assembled de novo transcriptome assembly using Trinity.
Start mapping reads and quantifying abundance simultaneously using Salmon.

## Entry 10: 2023-10-11:

- Transcriptomics DAY 2. 
- Copepod study 
  - effect of environment of Genetic Evolution 
  - signature of physiological adaptation in F2, F4, F11...
  - does the gene response in a given environment depend on the generation? We will conduct a statistical test for interaction between environmental conditions and generation. 
  - Interaction between environment and generation 
  
- Today we are... 
   - cleaning the raw sequence data 
   - generating and annotating a de novo reference transcriptome 
   
    

   
   
   
   